### PR TITLE
Installed show versions

### PR DESCRIPTION
**Pull request by r-vdp**
I'm on fire! This commit makes clyde show the installed version of a package in a search result if it differs from the repo version. See https://github.com/Kiwi/clyde/issues/#issue/72

### CODE REVIEW

**Comment by juster** [comment]
I have merged this on my local copy. However I spent a bit too much time rewriting sync_search. Now I have to make sure its colors match the origin and stuff. After that, I will push it to the master branch.

**Comment by juster** [comment]
Okay I have changed the colors a little bit... Could you tell me if you like them better than the old colors? Our changes are now on the 'test' branch. Can you try it out and tell me if you like the new color scheme? I never liked the old scheme much but maybe I am in the minority.

**Comment by r-vdp** [comment]
Looking good, the previous colors were a bit too flashy for my likings too.

**Comment by juster** [comment]
I have merged it and pushed a new version (0.03.14). I forgot that I combined your 4 commits into 1 so ... again the github automatic pull request won't know that this pull request is resolved. Thanks! Closing.

**Comment by juster** [comment]
BTW Here is all of your commits merged into one commit: 609877390837ef01149ab0afca57178c4ecd2cca

**Pull request closed without merging**
